apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  labels:
    app: react-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react_app
  template:
    metadata:
      labels:
        app: react_app
    spec:
      containers:
      - name: react
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://35.243.129.136:1337"
        imagePullPolicy: IfNotPresent
        image: us.gcr.io/proyecto-docker-301320/react-app
        ports:
        - containerPort: 3000